version: '3.9'

services:
  postgres:
    image: postgres:14.2
    ports:
      - '5433:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
